Environment:
  Database: Quickclass
Functions:
    UpdateProfile:
        Method: 
            - POST
        DataRoot: editProfile
        Tables: &profileTable
            Profile:
                Name: quickclass.profile
                Alias: p
                Default: true   
        Parameters: &profileParams
            ProfileID:
                Type: 
                    Integer:
                    OnFail: 
                        Code: 400
                        Message: Uh Oh
                Source: 
                    URL:
                        Pattern: /profile/(\d+)
                        Value: \1
                Identifier: True 
            FirstName:
                Type: 
                    String:
                Source: 
                    Payload:
                        Path: fname 
                        DataRoot: false 
                Column: fname 
            LastName: 
                Type: 
                    String:
                Column: lname
            profilePicture:
                Type: 
                    String:
            personalWebsiteUrl:
                Type: 
                    String:
            mediumUrl:
                Type: 
                    String:
                        Pattern: URL
        Query: 
            Type: UPDATE
    AddProfile:
        Method:
            - POST
        DataRoot: addProfile
        Tables: *profileTable
        Parameters: *profileParams
        Query:
            Type: INSERT