# yaml-language-server: $schema=mercury.schema.json
#Environment:
#  Database: Quickclass
Functions:
    AddProfile:
        Method: 
            - POST
        DataRoot: editProfile
        Tables: &profileTable
            Profile:
                Name: quickclass.profile
                Alias: p
                Default: true   
        Parameters: &profileParams
            lname:
                Type: 
                    String:
                        Pattern: 
                            Expression: /[A-Za-z]+/
            fname: 
                Type: 
                    String:
            profilePicture:
                Type: 
                    String:
                        Pattern: URL
            personalWebsiteUrl: 
                Type: 
                    String: 
                        Pattern: URL
        Query: INSERT
    UpdateProfile:
        Method:
            - PATCH
        DataRoot: addProfile
        Tables: *profileTable
        Parameters: 
            <<: *profileParams
            ProfileID:  
                Type: 
                    Integer:
                Source: 
                    URL:
                        Pattern: /profile/(\d+)
                        Value: \1
                Identifier: True 
        Query:
            Type: UPDATE
    AddPost:
        Method: 
            - POST
        Tables: 
            Posts:
                Name: quickclass.posts
                Alias: p
                Default: True
        DataRoot: addPost
        Parameters:
            PostContent:
                Type: 
                    String:
                        Length:
                            Lower: 0
                            Upper: 256000
            UserId:
                Name: userid
                Type:
                    Integer:
                        Bounds:
                            Lower: 1
                Identifier: True
            Foo:
                Type: 
                    String:
                Identifier: True
            Bar: 
                Type:
                    Integer:
                        Bounds: 
                            Lower: -1
                            Upper: 1
        Query: 
            Override: |
                    THIS IS NOT A VALID QUERY

                    THESE ARE THE TABLES:
                    {mercury::query::tables}
                    
                    THIS IS AN UPDATE:
                    {mercury::query::update::parameters}
                    
                    THIS IS A SELECT:
                    {mercury::query::select::parameters}
                    
                    THIS IS THE FIRST PART OF AN INSERT
                    {mercury::query::insert::columns}

                    AND THIS IS THE SECOND PART
                    {mercury::query::insert::values}

                    THIS IS THE CONDITION:
                    {mercury::query::identifier}


